### ISSUE TITLE
How to help with state detection!

### ISSUE THREAD

**Issue by JeffLIrion** [JeffLIrion/python-androidtv#12]
Assuming you're using the Home Assistant [Android TV](https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/androidtv) component, here's how you can help improve state detection. 

The component determines the state in the `update` method based on a collection of properties. You can see what those properties are by using the service `androidtv.adb_command` with `'GET_PROPERTIES'` as the `command` argument -- they will be logged at the INFO level. When HA version 0.90 gets released, you can read more about the `androidtv.adb_command` service at the bottom of the [Android TV documentation](https://www.home-assistant.io/components/media_player.androidtv); until then, you can check the [markdown source file](https://github.com/JeffLIrion/home-assistant.io/blob/f424fd37fdd1a791e8c84b190b8ae7f06ce7c102/source/_components/androidtv.markdown). 

I think the state detection logic might need to differ depending on the app. So open an app, send the `'GET_PROPERTIES'` command a few times while it's idle / on standby, playing, and paused, and try to figure out a better way to determine the state. Pull requests are welcome! 

If you're running this as a custom component, you can try out a different version of the package by modifying this script, running it, and restarting HA:

```bash
#!/bin/bash

export BRANCH="master"

rm -rf __pycache__
rm *.py
wget https://raw.githubusercontent.com/JeffLIrion/python-androidtv/$BRANCH/androidtv/__init__.py
wget https://raw.githubusercontent.com/JeffLIrion/python-androidtv/$BRANCH/androidtv/androidtv.py
wget https://raw.githubusercontent.com/JeffLIrion/python-androidtv/$BRANCH/androidtv/basetv.py
wget https://raw.githubusercontent.com/JeffLIrion/python-androidtv/$BRANCH/androidtv/constants.py
wget https://raw.githubusercontent.com/JeffLIrion/python-androidtv/$BRANCH/androidtv/firetv.py
```

**Comment by earth08** [comment]
I have tried using GET_PROPERTIES
i am not getting anything,
and also when 
my device is 
on idle it does shows idle
on home id does shows home
on any app it does shows apps
but when on play, paused it doesnt change
and also i when my device is turned on it doesnt change it color to dark 
( is it ok with color)

**Comment by earth08** [comment]
Thi I get when I get properties on playing video on vlc 
custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 'media_player.minim8s2': {'screen_on': True, 'awake': True, 'wake_lock_size': 3, 'media_session_state': 3, 'current_app': {'package': 'org.videolan.vlc', 'activity': 'org.videolan.vlc.gui.video.VideoPlayerActivity'}, 'audio_state': 'idle', 'device': 'hdmi', 'muted': False, 'volume_level': 4}

**Comment by JeffLIrion** [comment]
> Thi I get when I get properties on playing video on vlc
> custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 'media_player.minim8s2': {'screen_on': True, 'awake': True, 'wake_lock_size': 3, 'media_session_state': 3, 'current_app': {'package': 'org.videolan.vlc', 'activity': 'org.videolan.vlc.gui.video.VideoPlayerActivity'}, 'audio_state': 'idle', 'device': 'hdmi', 'muted': False, 'volume_level': 4}
> 
> On paused
> 
> custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 'media_player.minim8s2': {'screen_on': True, 'awake': True, 'wake_lock_size': 1, 'media_session_state': 2, 'current_app': {'package': 'org.videolan.vlc', 'activity': 'org.videolan.vlc.gui.video.VideoPlayerActivity'}, 'audio_state': 'idle', 'device': 'hdmi', 'muted': False, 'volume_level': 4}
> 
> What should be added or change in order to get proper player status

It looks like the `media_session_state` property is what you want to use. See here: https://github.com/JeffLIrion/python-androidtv/blob/38ac4fc7346d092d423aa0ecdfcd9110097c2648/androidtv/firetv.py#L150-L155

It would be great if you could fork the repo, make some changes, test it yourself, have others test it, and submit a pull request!

**Comment by JeffLIrion** [comment]
@earth08 the "state-detection" branch should yield better results.

**Comment by earth08** [comment]
Dear,
Sorry to tell you 
but i dont have any knowledge of coding.

**Comment by earth08** [comment]
when changing files as per statechange branck 
i get this
 File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/androidtv/media_player.py", line 95, in setup_platform
    from androidtv import setup
  File "/config/deps/lib/python3.7/site-packages/androidtv/__init__.py", line 6, in <module>
    from .androidtv import AndroidTV
  File "/config/deps/lib/python3.7/site-packages/androidtv/androidtv.py", line 128
    elif current_app = constants.APP_VLC:

**Comment by JeffLIrion** [comment]
You need to replace *ALL* the files. Your error is because you didn't replace constants.py.

**Comment by earth08** [comment]
I did replace all new files from python-androidtv statechange branch

**Comment by earth08** [comment]
This is what I get again,
Error while setting up platform androidtv
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/androidtv/media_player.py", line 95, in setup_platform
    from androidtv import setup
  File "/config/deps/lib/python3.7/site-packages/androidtv/__init__.py", line 6, in <module>
    from .androidtv import AndroidTV
  File "/config/deps/lib/python3.7/site-packages/androidtv/androidtv.py", line 128
    elif current_app = constants.APP_VLC:
                     ^
SyntaxError: invalid syntax

**Comment by JeffLIrion** [comment]
Sorry, I misread the traceback.  I fixed it.  Replace androidtv.py and it should work now.

**Comment by JeffLIrion** [comment]
@earth08 is it working now? Is the state detection working for VLC?

**Comment by earth08** [comment]
Sorry to reply it lately,
It is working,
But I found a new error,
When device is on home or any app in normal position, it shows paused.

**Comment by earth08** [comment]
this are the results from some few apps
it does works perfectly on vlc, but on home it shows as paused,
is there any comman wasys of getting the media state to verify and than link with current app?

here are
output at screensaver idle

2019-03-16 08:01:53 INFO (SyncWorker_4) [custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 
'media_player.minim8s2': {'screen_on': True, 'awake': False, 'wake_lock_size': -1, 
'media_session_state': None, 'current_app': None, 'audio_state': None, 'device': None, 'muted': None, 'volume_level': None}

outpt at homescreen 

2019-03-16 08:03:40 INFO (SyncWorker_6) [custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 
'media_player.minim8s2': {'screen_on': True, 'awake': True, 'wake_lock_size': 0,
'media_session_state': None, 'current_app': {'package': 'com.google.android.leanbacklauncher', 
'activity': 'com.google.android.leanbacklauncher.MainActivity'}, 'audio_state': 'idle', 'device': 'hdmi', 
'muted': False, 'volume_level': 9}

![home as puased](https://user-images.githubusercontent.com/4738580/54469867-624ebc00-47c4-11e9-8003-1bb2df151aab.png)

output on vlc it does shows as standby

2019-03-16 08:15:10 INFO (SyncWorker_9) [custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 
'media_player.minim8s2': {'screen_on': True, 'awake': True, 'wake_lock_size': 0, 
'media_session_state': None, 'current_app': {'package': 'org.videolan.vlc', 'activity': 'org.videolan.vlc.gui.tv.MainTvActivity'}, 
'audio_state': 'idle', 'device': 'hdmi', 'muted': False, 'volume_level': 9}

output when playing on vlc

2019-03-16 08:17:02 INFO (SyncWorker_11) [custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 
'media_player.minim8s2': {'screen_on': True, 'awake': True, 'wake_lock_size': 3, 
'media_session_state': 3, 'current_app': {'package': 'org.videolan.vlc', 'activity': 'org.videolan.vlc.gui.video.VideoPlayerActivity'}, 
'audio_state': 'idle', 'device': 'hdmi', 'muted': False, 'volume_level': 3}

output when vlc paused

2019-03-16 08:18:13 INFO (SyncWorker_12) [custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 
'media_player.minim8s2': {'screen_on': True, 'awake': True, 'wake_lock_size': 0, 
'media_session_state': 2, 'current_app': {'package': 'org.videolan.vlc', 'activity': 'org.videolan.vlc.gui.video.VideoPlayerActivity'},
'audio_state': 'idle', 'device': 'hdmi', 'muted': False, 'volume_level': 3}

**Comment by JeffLIrion** [comment]
I removed some posts that weren't directly related to state detection. 

I'm leaving it up to you and the community as a whole to collect data (as you've done) and implement better state detection. It's not that hard to modify the code, and as long as you don't have any syntax or programming errors, nothing catastrophic will happen if your state detection logic is flawed.

**Comment by earth08** [comment]
After some study on my output,
I found that many apps don’t provide a media_session_state,
The provide wake_lock_size,
So I modify some line is homeassistant updates like below,
Which is working good,
The only thing, with this changes, I found that, when device is off,
It does shows off, but activity is shown as standby.

        else:
            if wake_lock_size == 1: 
                state = constants.STATE_PAUSED 
            elif wake_lock_size == 2: 
                state = constants.STATE_PLAYING 
            else: 
                state = constants.STATE_STANDBY

#        else:
#            if wake_lock_size == 1:
#                state = constants.STATE_PLAYING
#            else:
#                state = constants.STATE_PAUSED

**Comment by earth08** [comment]
now as we have native androidtv component,
how to deal with dependencies for androidtv with statechange,

**Comment by BnMcG** [comment]
I've also found (with the Jellyfin app), that there are two wake locks when playing, and one when paused. Perhaps the default of "1 wake lock == paused" should be changed, or was that value chosen specifically?

**Comment by JeffLIrion** [comment]
> state off is now working well
> when device is turned off it does shows off for few seconds and after after that it shows unavailable.
> Is it behavior correct?
> should it be shown as off

'Unavailable' means that the ADB connection is not intact. Since HA can't turn the device on, I think unavailable is the appropriate state. But that has to do with the Home Assistant component, not this package.

**Comment by JeffLIrion** [comment]
> I've also found (with the Jellyfin app), that there are two wake locks when playing, and one when paused. Perhaps the default of "1 wake lock == paused" should be changed, or was that value chosen specifically?
> 
> This was on a Fire TV stick.

That is the logic used in the `firetv` package so that's what I used. 

I think the `wake_lock_size` behavior differs from app to app. I don't want to change the default behavior at this time, but you can submit a pull request with logic that is specific to the Jellyfish app. It's pretty simple to do:

1. In constants.py, add an `APP_JELLYFISH = <Jellyfish app ID>` constant. Add its friendly name to the `APPS` dictionary (i.e., `APP_JELLYFISH: 'Jellyfish'`). For both of these, please follow alphabetical order. 
2. In firetv.py, in the `update` method, add in a block for your state detection. 

   ```python
   # Jellyfish
   elif current_app == constants.APP_JELLYFISH:
       ...
   ```

**Comment by BnMcG** [comment]
Great, I'll do that shortly

**Comment by BnMcG** [comment]
I've raised #17 to fix this for Jellyfin

**Comment by Molodax** [comment]
Hi,

Unfortunately, some changes in the state logic made it "playing" all the time instead of "pause" for my case (Philips TV). It was some version when it was correct playing/pause section, but I cannot find that vestion anymore.
I run the component on hassio and am trying to contribute to the states detection, however, get this output:

`2019-03-31 19:36:03 INFO (SyncWorker_7) [custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 'media_player.android_tv': '/system/bin/sh: GET_PROPERTIES: not found\n'`

Any idea what is wrong?

**Comment by JeffLIrion** [comment]
> Hi,
> 
> Unfortunately, some changes in the state logic made it "playing" all the time instead of "pause" for my case (Philips TV). It was some version when it was correct playing/pause section, but I cannot find that vestion anymore.
> I run the component on hassio and am trying to contribute to the states detection, however, get this output:
> 
> `2019-03-31 19:36:03 INFO (SyncWorker_7) [custom_components.androidtv.media_player] Output of command 'GET_PROPERTIES' from 'media_player.android_tv': '/system/bin/sh: GET_PROPERTIES: not found\n'`
> 
> Any idea what is wrong?

You're not using the right component.  Use the official component.  

https://github.com/home-assistant/home-assistant/blob/50a0504e07c971874a1bedf99ebd17a5383c88b1/homeassistant/components/androidtv/media_player.py#L316-L317

**Comment by lolouk44** [comment]
Just chirping in to confirm that 
```
                 if media_session_state == 2: 
                     state = constants.STATE_PAUSED 
                 elif media_session_state == 3: 
                     state = constants.STATE_PLAYING 
                 else: 
                     state = constants.STATE_STANDBY 
```
Is the way to go for Amazon Video too on a Fire TV 4K
I'll try and do a PR (never done before) and see how it goes

**Comment by t0mmy44-h** [comment]
Hi Jeff, I have a Kogan TV (I think it's a rebranded TCL, or similar... not really sure who manufactured it as Kogan uses a few OEMs) and currently the `hdmi_input` detection doesn't work for me.

The following adb command does work, if I patch it into the python on my instance:

`dumpsys hdmi_control | grep -o "mActiveRoutingPath: 0x[1-9]" | grep -o '[1-9]'`

How can I go about getting this into the package for TVs that it works on?

**Comment by JeffLIrion** [comment]
This issue needs to be done first: https://github.com/JeffLIrion/python-androidtv/issues/255

After that's done, it shouldn't be too hard to customize the command used the get the HDMI input and the code that processes the result.
