### ISSUE TITLE
lots of logs when device is turn off

### ISSUE THREAD

**Issue by earth08** [JeffLIrion/python-androidtv#15]
when device is turnoff
the error floods the log file
error shown

```
2019-03-20 10:31:58 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.minim8s2 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 348, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/androidtv/media_player.py", line 186, in _adb_exception_catcher
    return func(self, *args, **kwargs)
  File "/config/custom_components/androidtv/media_player.py", line 342, in update
    self.aftv.update()
  File "/config/deps/lib/python3.7/site-packages/androidtv/androidtv.py", line 100, in update
    screen_on, awake, wake_lock_size, media_session_state, _current_app, audio_state, device, muted, volume_level = self.get_properties(lazy=True)
  File "/config/deps/lib/python3.7/site-packages/androidtv/androidtv.py", line 341, in get_properties
    "dumpsys audio")
  File "/config/deps/lib/python3.7/site-packages/androidtv/basetv.py", line 122, in _adb_shell_pure_python_adb
    return self._adb_device.shell(cmd)
  File "/usr/local/lib/python3.7/site-packages/adb_messenger/command/transport/__init__.py", line 20, in shell
    conn = self.create_connection(timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/adb_messenger/device.py", line 45, in create_connection
    self.transport(conn)
  File "/usr/local/lib/python3.7/site-packages/adb_messenger/command/transport/__init__.py", line 15, in transport
    connection.send(cmd)
  File "/usr/local/lib/python3.7/site-packages/adb_messenger/connection.py", line 77, in send
    return self._check_status()
  File "/usr/local/lib/python3.7/site-packages/adb_messenger/connection.py", line 83, in _check_status
    raise RuntimeError("ERROR: {} {}".format(repr(recv), error))
RuntimeError: ERROR: 'FAIL' 0025device '192.168.11.37:5555' not found
2019-03-20 10:32:09 ERROR (MainThread) [homeassistant.helpers.entity] Update for media_player.minim8s2 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 348, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/androidtv/media_player.py", line 186, in _adb_exception_catcher
    return func(self, *args, **kwargs)
  File "/config/custom_components/androidtv/media_player.py", line 342, in update
    self.aftv.update()
  File "/config/deps/lib/python3.7/site-packages/androidtv/androidtv.py", line 100, in update
    screen_on, awake, wake_lock_size, media_session_state, _current_app, audio_state, device, muted, volume_level = self.get_properties(lazy=True)
  File "/config/deps/lib/python3.7/site-packages/androidtv/androidtv.py", line 341, in get_properties
    "dumpsys audio")
  File "/config/deps/lib/python3.7/site-packages/androidtv/basetv.py", line 122, in _adb_shell_pure_python_adb
    return self._adb_device.shell(cmd)
  File "/usr/local/lib/python3.7/site-packages/adb_messenger/command/transport/__init__.py", line 20, in shell
    conn = self.create_connection(timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/adb_messenger/device.py", line 45, in create_connection
    self.transport(conn)
  File "/usr/local/lib/python3.7/site-packages/adb_messenger/command/transport/__init__.py", line 15, in transport
    connection.send(cmd)
  File "/usr/local/lib/python3.7/site-packages/adb_messenger/connection.py", line 77, in send
    return self._check_status()
  File "/usr/local/lib/python3.7/site-packages/adb_messenger/connection.py", line 83, in _check_status
    raise RuntimeError("ERROR: {} {}".format(repr(recv), error))
RuntimeError: ERROR: 'FAIL' 0025device '192.168.11.37:5555' not found
```

**Comment by JeffLIrion** [comment]
Try this file and let me know if it fixes it.  

https://raw.githubusercontent.com/JeffLIrion/home-assistant/androidtv-log-errors/homeassistant/components/androidtv/media_player.py

**Comment by earth08** [comment]
Ok,
Now no more flooding.

**Comment by earth08** [comment]
Logs have stated flooding my log file.
In patch #16

**Comment by JeffLIrion** [comment]
This is an issue in the HA component. Please file an issue there and link this PR: https://github.com/home-assistant/home-assistant/pull/22268
